### ISSUE TITLE
Consider using fewer modules

### ISSUE THREAD

**Issue by lpil** [grottohub/carpenter#1]
Hello!

Thanks for making this library 💜 

I was looking at using it today and I found it a bit hard to understand how to use it. When you open the documentation there's a lot of modules, most of which don't seem to hold much of anything.

I think it would be a lot nicer if the package had fewer modules, ideally just one. That way it's clear where the programmer should go, and there's much less boilerplate in terms of imports etc.

Thanks,
Louis

**Comment by grottohub** [comment]
alright, lemme know what you think! tried to make the API as straightforward as possible. once I get more comfortable with erlang itself i'll go through and add some extra safety around some of the operations, along with implementing a lot of the missing features. but for a `set` or `ordered_set`, things should be at minimal functionality

**Comment by lpil** [comment]
Thank you!!
